[platformio]
core_dir = ../../../.platformio-home
default_envs = native

[env:native]
platform = native
build_flags =
  -pipe
lib_deps =
  EmbeddedMusicMonophonic=file:///tmp/EmbeddedMusicMonophonic-0.1.0.tar.gz
