[platformio]
core_dir = ../../../.platformio-home
default_envs = m5stack-core-gray

[env:m5stack-core-gray]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = m5stack-core-esp32
framework = arduino
board_build.partitions = huge_app.csv
build_flags =
  -pipe
lib_deps =
  fcz2/amy-synth-m5@0.1.2
