[platformio]
core_dir = ../../../.platformio-home
default_envs = m5stack-core-gray

[env:m5stack-core-gray]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = m5stack-core-esp32
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_build.partitions = huge_app.csv
build_flags =
  -pipe
  -D BLE_MIDI_DEVICE_NAME='"M5 Gray Speaker"'
lib_deps =
  fcz2/ble-midi-input@0.3.0
  fcz2/monophonic-instrument@0.1.2
  fcz2/m5-tone-output@0.1.2
  m5stack/M5Unified@0.2.17
lib_ignore =
  ArduinoBLE
  Arduino_SpiNINA
