[platformio]
default_envs = m5stick-cplus2

[env:m5stick-cplus2]
platform = platformio/espressif32@7.0.1
board = m5stick-cplus2
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
lib_deps =
  EmbeddedMusicBleMidiInput=https://github.com/fczuardi/midi-receiver.git#60fce82734d3a81f659c15de2f8ee0b7d97c20ff
  EmbeddedMusicBuzzerInstrument=https://github.com/fczuardi/buzzer-instrument.git#42ec33d4ad347babe7f0dd3bed7db40b1b426ad6
