[platformio]
default_envs = m5stick-cplus2

[env:m5stick-cplus2]
platform = platformio/espressif32@7.0.1
board = m5stick-cplus2
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
lib_deps =
  EmbeddedMusicBleMidiInput=https://github.com/fczuardi/midi-receiver.git#84b620aecba69026a1b485ceb2d23b18f7be0f61
  EmbeddedMusicBuzzerInstrument=https://github.com/fczuardi/buzzer-instrument.git#8535f3434d4f00dd35f69dc8b2a7c88030460c12
